[jokes]

golf = [
    "An interesting thing about golf is that no matter how badly you play, it’s always possible to get worse.",
    "Golf is a game invented by God to punish people who retire early.",
    "I like big putts and I cannot lie.",
    "There are three ways to improve your golf game: take lessons, practice constantly… or start cheating.",
    "Why do golf announcers whisper? Because they don’t want to wake up the people watching.",
    "I play in the low 80s. If it’s any hotter than that, I won’t play.",
    "Golf: a 5-mile walk punctuated with disappointments.",
    "If your opponent can’t remember if he shot a six or a seven on a hole, chances are he had an eight on it.",
    "In primitive society, when native tribes beat the ground with clubs and yelled, it was called witchcraft; today, in civilized society, it’s called golf.",
    "Golf can best be defined as an endless series of tragedies obscured by the occasional miracle.",
    "To some golfers, the greatest handicap is the ability to add correctly.",
    "Golf was once a rich man’s sport, but now it has millions of poor players!",
    "The difference between a whiff and a practice swing - no one curses after a practice swing.",
    "You should always try before you buy, especially when buying a putter. Never buy a putter until you’ve seen how well you can throw it.",
    "The higher the handicap of the golfer, the more likely it is that he’ll be telling you what you should be doing to fix your game.",
    "Golf brings out the 3-year-old in us – we struggle to count past 5.",
    "Golf balls are like eggs. They’re both white, sold by the dozen, and a week later you have to go out and buy more.",
    "Golf is what you play when you’re too out of shape to play other sports.",
    "Golf was once a rich man’s sport, but now it has millions of poor players!",
    "Where can you find a golfer on a Saturday night? Clubbing!",
    "“I have a tip that can take five strokes off anyone’s game: It’s called an eraser.” - Arnold Palmer",
    "“While playing golf today I hit two good balls. I stepped on a rake.” - Henry Youngman",
    "“If you drink, don’t drive. Don’t even putt.” - Dean Martin",
    "“It took me seventeen years to get three thousand hits in baseball. It took one afternoon on the golf course.” - Hank Aaron",
    "“You’ve just got one problem. You stand too close to the ball after you’ve hit it.” - Sam Snead",
    "“We learn so many things from golf – how to suffer, for instance.” - Bruce Lansky",
    "“If you are caught on a golf course during a storm and are afraid of lightning, hold up a 1-iron. Not even God can hit a 1-iron” - Lee Trevino",
    "“If you watch a game, it's fun. If you play at it, it's recreation. If you work at it, it's golf.” - Bob Hope",
    "“Golf is a game in which you yell four, shoot six, and write down five.” - Paul Harvey",
    "“Pressure is when you play $5 a hole with only $2 in your pocket.” - Lee Trevino",
    "“The income tax has made more liars out of the American people than golf has.” - Will Rogers",
    "“Give me the fresh air, a beautiful partner, and a nice round of golf, and you can keep the fresh air and the round of golf.” - Jack Benny",
    "“Golf is a game invented by the same people who think music comes out of a bagpipe” - Lee Trevino",
    "“It's good sportsmanship to not pick up lost golf balls while they are still rolling.” - Mark Twain",
    "“If you are going to throw a club, it is important to throw it ahead of you, down the fairway, so you don't have to waste energy going back to pick it up.” - Tommy Bolt",
    "“If a lot of people gripped a knife and fork as poorly as they do a golf club, they'd starve to death.” - Sam Snead",
    "“The only sure rule in golf is he who has the fastest golf cart never has to play the bad lie.” - Mickey Mantle",
    "“I know I am getting better at golf because I am hitting fewer spectators.” - Gerald Ford",
    "“Golf is a puzzle without an answer. I've played the game for 40 years and I still haven't the slightest idea how to play.” - Gary Player",
    "“I would like to deny all allegations by Bob Hope that during my last game of golf, I hit an eagle, a birdie, an elk and a moose.” - Gerald Ford",
    "“Golf tips are like aspirin. One may do you good, but if you swallow the whole bottle you will be lucky to survive.” - Harvey Penick",
    "“It’s alive, this swing, a living sculpture! And down through contact, always down, striking the ball crisply, with character. A tuning fork goes off in your heart and your balls.” - Roy McAvoy (Tin Cup)",
    "“I play golf with friends sometimes, but there are never friendly games.” - Ben Hogan",
    "If I hit it right, it's a slice. If I hit it left, it's a hook. If I hit it straight, it's a miracle.",
    "In golf, you can hit a 2-acre fairway 10-percent of the time, but hit a 2-inch branch 90-percent of the time.",
    "The game of golf is 90-percent mental and 10-percent mental.",
    "Golfer: The doctor says I can't play golf. Caddie: Oh, he's played with you, too, eh?",
    "Golfer: That can't be my ball, it looks too old. Caddie: It's been a long time since we started.",
    "A good golf partner is one who's always a little bit worse than you are.",
    "Golf is an odd game! You hit down to make the ball go up. You swing left and the ball goes right. The lowest score wins. And on top of that, the winner buys the drinks.",
    "What are the four worst words you could hear during a game of golf? “It's still your turn!”",
    "It takes a serious amount of balls to golf like I do.",
    "What does a golfer like to hear from his wife? “Talk birdie to me.”",
    "Where do ghouls and ghosts play their golf? On a golf corpse.",
    "Why was Cinderella such a terrible golfer? Her coach was a pumpkin.",
    "Golf: A seven-mile walk punctuated with frequent disappointments.",
    "Many a golfer prefers a golf cart to a caddy because it cannot count, criticize, or laugh.",
    "The worst day on the course is better than your best day in the office.",
    "What did you get on your last hole? Depressed!",
    "What did Master Yoda say when Luke sliced the ball onto the next fairway over? “May the ‘Fores’ be with you…”",
    "“My doctor told me I can’t play golf.” — “Oh, when did he play with you?”",
    "What’s the difference between the g-spot and a golf ball? A guy will spend 10 minutes trying to find his lost golf ball.",
    "What’s one tip all golfers should follow to improve their game? Go back in time and start playing at a younger age.",
    "Why didn’t the golfer finish his homework? He couldn’t stop puttzing around!",
    "The most redundant thing on a golf course is a ball-washer on a hole with water hazards.",
    "What did Chamillionaire say when he came in a stroke under par? “Tryna catch me ridin’ birdie!”",
    "Why don’t grasshoppers play golf? They like cricket better.",
    "Why does the temperature on the course rise after a long tournament ends? All the fans are gone!",
    "“My wife said I play so much golf it’s driving a wedge between us.”",
    "“I came home to my wife in lingerie… she said I could tie her up and do whatever I wanted. So I tied her to the chair and went to the driving range.”",
    "Which pro golfers can jump higher than the flag? All of them…. the flag can’t jump.",
    "I told my buddy I got a new set of clubs for my wife. He said, “Sounds like a good trade!”",
    "Why are computers such naturally good golfers? They have a hard drive.",
    "Why do golfers hate cake? Because they might get a slice.",
    "The problem with your game is your loft. My loft? Lack Of Freaking Talent.",
    "Golfer: Hey do you know where they are building that new Walmart? Buddy: No, where? Golfer: Between my drive and yours.",
    "I’m not over the hill. I’m just on the back nine.",
    "Golfers aren’t happy unless they’re teed off!",
    "Golf is like marriage: If you take yourself too seriously it won’t work… and both are expensive.",
    "If you golf on election day, be sure to cast an absent-tee ballot.",
    "Golf forth, and prosper.",
    "Careful there, putter fingers.",
    "A land par, par away.",
    "What did the golfer say to the hip-hop dancer? Every day I'm Schauffele.",
    "How do you know a golfer is cheating on his wife? He always puts his driver in the wrong bag.",
    "What do you call a lion playing golf? Roarin' Mcllroy",
    "Why did Tarzan spend so much time on the golf course? He was perfecting his swing.",
    "I hate golf courses with too many trees, I go to great links to avoid them.",
    "Did you hear that Subway is opening a mini-golf course at some of their restaurants? I tried it out, but it wasn’t very good. It was sub-par.",
    "When golfers make golf jokes – Are they just meta-fores?",
    "Who’s the best person at the golf course to get to make coffee? The groundskeeper!",
    "How many golfers does it take to change a light bulb? FORE!",
    "I'm not a bad putter, I just can't catch a break.",
    "What type of golf game did the fur traders play in the old days? A skins match.",
    "If your opponent has trouble remembering whether he shot a six or a seven, it means he probably shot an eight.",
    "Golfer A: I played World War II golf—out in 39 and home in 45. Golfer B: I played Civil War golf—out in 61 and home in 65.",
    "Bad? I’ll tell you how bad he is. In his bag he carries flares, a compass and emergency rations.",
    "The way he plays they should put the flags on the greens at half-mast.",
    "It seems to me that at times the hardest thing about golf is being allowed out of the house to play it.",
    "It’s a strange world isn’t it? You hire someone to mow your lawn, so that you’ll have time to play golf for the exercise.",
    "He’s too fat to play. If he places the ball where he can hit it, he can’t see it. If he places it where he can see it, he can’t hit it.",
    "Real golfers have two handicaps: one for braggin' and one for bettin'.",
    "Real golfers don't cry when they line up their fourth putt.",
    "Golfer: Please stop checking your watch all the time, it's distracting! Caddie: This isn't a watch, ma'am, it's a compass.",
    "How’s golf like fishing? Both mysteriously encourage exaggeration.",
    "I've seen better swings on a porch.",
    "That was a really good shot ..........................for you!!"
]
